# Generated by Django 5.0.2 on 2024-03-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('sport', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=30)),
                ('team', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='FootballPlayer',
        ),
    ]
