# Generated by Django 5.0.2 on 2024-03-06 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PageApp', '0002_players_delete_footballplayer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Song',
            new_name='Songs',
        ),
    ]
