# Generated by Django 5.0.2 on 2024-03-06 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PageApp', '0003_rename_song_songs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Movies',
        ),
    ]
