# Generated by Django 5.0.2 on 2024-03-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageApp', '0004_rename_movie_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='players',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
